server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/pauldev17/microservices-01
          search-paths: config-data
  application:
    name: config-service
